請就所提供的資料以財務特徵(X1-X95)預測公司是否破產(Y)，並新增衍生變數，比較不同的機器學習模型，並說明分析結果

(Precision, Recall, Accuracy若未達0.9，請說明如何發展衍生變數使模式具有良好的預測能力)。

類別:
Net Income Flag(94)、Liability-Assets Flag(85)、Bankrupt?

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import statsmodels.api as sm
from scipy import stats
from sklearn import metrics

In [ ]:
data=pd.read_excel("/content/drive/MyDrive/機器學習/闖關/預測公司破產資料.xlsx")

因為Bankrupt?=1的比數很少，故模型要做出來準確很難

In [ ]:
f=data.groupby('Bankrupt?')
frequence=f.size()
flist=pd.DataFrame(frequence,columns=['Frequence_是否破產'])
f=data.groupby('Bankrupt?')
percentage=f.size()/len(data)
plist=pd.DataFrame(percentage,columns=['Percentage_是否破產'])
a=flist.merge(plist,on = 'Bankrupt?')
a

Frequence_是否破產  Percentage_是否破產
Bankrupt?                                 
0.000                6599            0.968
1.000                 220            0.032

#原始資料 混淆矩陣
#當Bankrupt?=1時Precision, Recall的值小於0.9所以須新增衍生變數使其變好看

In [ ]:
#給下面自變數X取除了Bankrupt?以外的欄位名稱，不然一個一個打會打到亂掉
a=data.copy()
a=a.drop('Bankrupt?',axis=1)

In [ ]:
X=a[a.columns]
y=data['Bankrupt?']
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25 ,random_state=333)

決策樹

In [ ]:
from sklearn import tree
DT = tree.DecisionTreeClassifier(max_depth=10)
DT= DT.fit(X, y)

In [ ]:
#訓練
DT_pred= DT.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,DT_pred))
print("======================================================\n")
print(classification_report(y_train,DT_pred))

[[4937    0]
 [  29  148]]

              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00      4937
         1.0       1.00      0.84      0.91       177

    accuracy                           0.99      5114
   macro avg       1.00      0.92      0.95      5114
weighted avg       0.99      0.99      0.99      5114



In [ ]:
#測試
DT_pred= DT.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,DT_pred))
print("======================================================\n")
print(classification_report(y_test,DT_pred))

[[1662    0]
 [   9   34]]

              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00      1662
         1.0       1.00      0.79      0.88        43

    accuracy                           0.99      1705
   macro avg       1.00      0.90      0.94      1705
weighted avg       0.99      0.99      0.99      1705



隨機森林

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=15,max_features="sqrt",oob_score=True,random_state=3)
RF.fit(X_train.values,y_train.values)

/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:560: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(


RandomForestClassifier(max_features='sqrt', n_estimators=15, oob_score=True,
                       random_state=3)

In [ ]:
#訓練
RF_pred= RF.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,RF_pred))
print("======================================================\n")
print(classification_report(y_train,RF_pred))

[[4937    0]
 [   9  168]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      4937
         1.0       1.00      0.95      0.97       177

    accuracy                           1.00      5114
   macro avg       1.00      0.97      0.99      5114
weighted avg       1.00      1.00      1.00      5114



/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


In [ ]:
#測試
RF_pred= RF.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,RF_pred))
print("======================================================\n")
print(classification_report(y_test,RF_pred))

[[1642   20]
 [  31   12]]

              precision    recall  f1-score   support

         0.0       0.98      0.99      0.98      1662
         1.0       0.38      0.28      0.32        43

    accuracy                           0.97      1705
   macro avg       0.68      0.63      0.65      1705
weighted avg       0.97      0.97      0.97      1705



/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


羅吉斯回歸

In [ ]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(solver='liblinear')
LR.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [ ]:
#訓練
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_train)
print(confusion_matrix(y_train,LR_pred))
print("======================================================\n")
print(classification_report(y_train,LR_pred))

[[4908   29]
 [ 172    5]]

              precision    recall  f1-score   support

         0.0       0.97      0.99      0.98      4937
         1.0       0.15      0.03      0.05       177

    accuracy                           0.96      5114
   macro avg       0.56      0.51      0.51      5114
weighted avg       0.94      0.96      0.95      5114



In [ ]:
#測試
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_test)
print(confusion_matrix(y_test,LR_pred))
print("======================================================\n")
print(classification_report(y_test,LR_pred))

[[1658    4]
 [  43    0]]

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.99      1662
         1.0       0.00      0.00      0.00        43

    accuracy                           0.97      1705
   macro avg       0.49      0.50      0.49      1705
weighted avg       0.95      0.97      0.96      1705



KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3) #K值(n_neighbors)預設為5
knn.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
#訓練
knn_pred= knn.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,knn_pred))
print("======================================================\n")
print(classification_report(y_train,knn_pred))

[[4933    4]
 [ 156   21]]

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98      4937
         1.0       0.84      0.12      0.21       177

    accuracy                           0.97      5114
   macro avg       0.90      0.56      0.60      5114
weighted avg       0.96      0.97      0.96      5114



In [ ]:
#測試
knn_pred= knn.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,knn_pred))
print("======================================================\n")
print(classification_report(y_test,knn_pred))

[[1659    3]
 [  29   14]]

              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      1662
         1.0       0.82      0.33      0.47        43

    accuracy                           0.98      1705
   macro avg       0.90      0.66      0.73      1705
weighted avg       0.98      0.98      0.98      1705



SVM(因資料沒處理過所以會跑很慢，故不採用)

In [ ]:
# from sklearn import svm 
# clf = svm.SVC(kernel = 'linear') 
# clf.fit(X_train,y_train) 

In [ ]:
# #訓練
# from sklearn.metrics import classification_report,confusion_matrix
# clf_tpred= clf.predict(X_train)
# print(confusion_matrix(y_train,clf_tpred))
# print("======================================================\n")
# print(classification_report(y_train,clf_tpred))

In [ ]:
# #測試
# clf_pred= clf.predict(X_test)
# print(confusion_matrix(y_test,clf_pred))
# print("======================================================\n")
# print(classification_report(y_test,clf_pred))

#標準化&卡方檢定t檢定

In [ ]:
#最小最大值標準化
from sklearn import preprocessing
minmax=preprocessing.MinMaxScaler()
dataMinMax=minmax.fit_transform(data)
dataMinMax=pd.DataFrame(dataMinMax,columns=['Bankrupt?', ' ROA(C) before interest and depreciation before interest',' ROA(A) before interest and % after tax',
       ' ROA(B) before interest and depreciation after tax',' Operating Gross Margin', ' Realized Sales Gross Margin',' Operating Profit Rate', 
       ' Pre-tax net Interest Rate',' After-tax net Interest Rate',' Non-industry income and expenditure/revenue',
       ' Continuous interest rate (after tax)', ' Operating Expense Rate',' Research and development expense rate', ' Cash flow rate',
       ' Interest-bearing debt interest rate', ' Tax rate (A)',' Net Value Per Share (B)', ' Net Value Per Share (A)',
       ' Net Value Per Share (C)', ' Persistent EPS in the Last Four Seasons',' Cash Flow Per Share', ' Revenue Per Share (Yuan 瞼)',
       ' Operating Profit Per Share (Yuan 瞼)',' Per Share Net profit before tax (Yuan 瞼)',' Realized Sales Gross Profit Growth Rate',
       ' Operating Profit Growth Rate', ' After-tax Net Profit Growth Rate',' Regular Net Profit Growth Rate', ' Continuous Net Profit Growth Rate',
       ' Total Asset Growth Rate', ' Net Value Growth Rate',' Total Asset Return Growth Rate Ratio', ' Cash Reinvestment %',
       ' Current Ratio', ' Quick Ratio', ' Interest Expense Ratio',' Total debt/Total net worth', ' Debt ratio %', ' Net worth/Assets',
       ' Long-term fund suitability ratio (A)', ' Borrowing dependency',' Contingent liabilities/Net worth',' Operating profit/Paid-in capital',
       ' Net profit before tax/Paid-in capital',' Inventory and accounts receivable/Net value', ' Total Asset Turnover',
       ' Accounts Receivable Turnover', ' Average Collection Days',' Inventory Turnover Rate (times)', ' Fixed Assets Turnover Frequency',
       ' Net Worth Turnover Rate (times)', ' Revenue per person',' Operating profit per person', ' Allocation rate per person',
       ' Working Capital to Total Assets', ' Quick Assets/Total Assets',' Current Assets/Total Assets', ' Cash/Total Assets',
       ' Quick Assets/Current Liability', ' Cash/Current Liability',' Current Liability to Assets', ' Operating Funds to Liability',
       ' Inventory/Working Capital', ' Inventory/Current Liability',' Current Liabilities/Liability', ' Working Capital/Equity',
       ' Current Liabilities/Equity', ' Long-term Liability to Current Assets',' Retained Earnings to Total Assets', ' Total income/Total expense',
       ' Total expense/Assets', ' Current Asset Turnover Rate',' Quick Asset Turnover Rate', ' Working capitcal Turnover Rate',
       ' Cash Turnover Rate', ' Cash Flow to Sales', ' Fixed Assets to Assets',' Current Liability to Liability', ' Current Liability to Equity',
       ' Equity to Long-term Liability', ' Cash Flow to Total Assets',' Cash Flow to Liability', ' CFO to Assets', ' Cash Flow to Equity',
       ' Current Liability to Current Assets', ' Liability-Assets Flag',' Net Income to Total Assets', ' Total assets to GNP price',
       ' No-credit Interval', ' Gross Profit to Sales'," Net Income to Stockholder's Equity", ' Liability to Equity',
       ' Degree of Financial Leverage (DFL)',' Interest Coverage Ratio (Interest expense to EBIT)',' Net Income Flag', ' Equity to Liability'])
dataMinMax.head()

Bankrupt?   ROA(C) before interest and depreciation before interest  \
0      1.000                                              0.371          
1      1.000                                              0.464          
2      1.000                                              0.426          
3      1.000                                              0.400          
4      1.000                                              0.465          

    ROA(A) before interest and % after tax  \
0                                    0.424   
1                                    0.538   
2                                    0.499   
3                                    0.451   
4                                    0.538   

    ROA(B) before interest and depreciation after tax  \
0                                              0.406    
1                                              0.517    
2                                              0.472    
3                                              0.458    
4                                              0.522    

    Operating Gross Margin   Realized Sales Gross Margin  \
0                    0.601                         0.601   
1                    0.610                         0.610   
2                    0.601                         0.601   
3                    0.584                         0.584   
4                    0.599                         0.599   

    Operating Profit Rate   Pre-tax net Interest Rate  \
0                   0.999                       0.797   
1                   0.999                       0.797   
2                   0.999                       0.796   
3                   0.999                       0.797   
4                   0.999                       0.797   

    After-tax net Interest Rate   Non-industry income and expenditure/revenue  \
0                         0.809                                         0.303   
1                         0.809                                         0.304   
2                         0.808                                         0.302   
3                         0.809                                         0.303   
4                         0.809                                         0.303   

   ...   Net Income to Total Assets   Total assets to GNP price  \
0  ...                        0.717                       0.000   
1  ...                        0.795                       0.000   
2  ...                        0.775                       0.000   
3  ...                        0.740                       0.000   
4  ...                        0.795                       0.000   

    No-credit Interval   Gross Profit to Sales  \
0                0.623                   0.601   
1                0.624                   0.610   
2                0.624                   0.601   
3                0.623                   0.584   
4                0.624                   0.599   

    Net Income to Stockholder's Equity   Liability to Equity  \
0                                0.828                 0.290   
1                                0.840                 0.284   
2                                0.837                 0.290   
3                                0.835                 0.282   
4                                0.840                 0.279   

    Degree of Financial Leverage (DFL)  \
0                                0.027   
1                                0.265   
2                                0.027   
3                                0.027   
4                                0.025   

    Interest Coverage Ratio (Interest expense to EBIT)   Net Income Flag  \
0                                              0.564               0.000   
1                                              0.570               0.000   
2                                              0.564               0.000   
3                                              0.565               0.000   
4                        

In [ ]:
#1類對多量的t檢定

data_set2=[' ROA(C) before interest and depreciation before interest',' ROA(A) before interest and % after tax',' ROA(B) before interest and depreciation after tax',
       ' Operating Gross Margin', ' Realized Sales Gross Margin',' Operating Profit Rate', ' Pre-tax net Interest Rate',' After-tax net Interest Rate',
       ' Non-industry income and expenditure/revenue',' Continuous interest rate (after tax)', ' Operating Expense Rate',' Research and development expense rate',
       ' Cash flow rate',' Interest-bearing debt interest rate', ' Tax rate (A)',' Net Value Per Share (B)', ' Net Value Per Share (A)',
       ' Net Value Per Share (C)', ' Persistent EPS in the Last Four Seasons',' Cash Flow Per Share', ' Revenue Per Share (Yuan 瞼)',
       ' Operating Profit Per Share (Yuan 瞼)',' Per Share Net profit before tax (Yuan 瞼)',' Realized Sales Gross Profit Growth Rate',
       ' Operating Profit Growth Rate', ' After-tax Net Profit Growth Rate',' Regular Net Profit Growth Rate', ' Continuous Net Profit Growth Rate',
       ' Total Asset Growth Rate', ' Net Value Growth Rate',' Total Asset Return Growth Rate Ratio', ' Cash Reinvestment %',
       ' Current Ratio', ' Quick Ratio', ' Interest Expense Ratio',' Total debt/Total net worth', ' Debt ratio %', ' Net worth/Assets',
       ' Long-term fund suitability ratio (A)', ' Borrowing dependency',' Contingent liabilities/Net worth',' Operating profit/Paid-in capital',
       ' Net profit before tax/Paid-in capital',' Inventory and accounts receivable/Net value', ' Total Asset Turnover',' Accounts Receivable Turnover',
       ' Average Collection Days',' Inventory Turnover Rate (times)', ' Fixed Assets Turnover Frequency',' Net Worth Turnover Rate (times)',
       ' Revenue per person',' Operating profit per person', ' Allocation rate per person',' Working Capital to Total Assets',
       ' Quick Assets/Total Assets',' Current Assets/Total Assets', ' Cash/Total Assets',' Quick Assets/Current Liability', ' Cash/Current Liability',
       ' Current Liability to Assets', ' Operating Funds to Liability',' Inventory/Working Capital', ' Inventory/Current Liability',
       ' Current Liabilities/Liability', ' Working Capital/Equity',' Current Liabilities/Equity', ' Long-term Liability to Current Assets',
       ' Retained Earnings to Total Assets', ' Total income/Total expense',' Total expense/Assets', ' Current Asset Turnover Rate',
       ' Quick Asset Turnover Rate', ' Working capitcal Turnover Rate',' Cash Turnover Rate', ' Cash Flow to Sales', ' Fixed Assets to Assets',
       ' Current Liability to Liability', ' Current Liability to Equity',' Equity to Long-term Liability', ' Cash Flow to Total Assets',
       ' Cash Flow to Liability', ' CFO to Assets', ' Cash Flow to Equity',' Current Liability to Current Assets',' Net Income to Total Assets',
       ' Total assets to GNP price',' No-credit Interval', ' Gross Profit to Sales'," Net Income to Stockholder's Equity",
       ' Liability to Equity',' Degree of Financial Leverage (DFL)',' Interest Coverage Ratio (Interest expense to EBIT)',' Equity to Liability']
name=[]
alist=[]
pvlist=[]
for i in range(len(data_set2)):
  (a,pv)=stats.ttest_ind(dataMinMax[data_set2[i]][dataMinMax['Bankrupt?']==0],dataMinMax[data_set2[i]][dataMinMax['Bankrupt?']==1])
  name.append(data_set2[i])
  alist.append(a)
  pvlist.append(pv)
pd.set_option('display.float_format',lambda x:'%.3f'%x)
result=pd.DataFrame(alist,name,columns=['t_value'])
result.insert(1,'p_value',pvlist)
result=result.sort_values(by=['p_value'])[::1]
result

t_value  p_value
 Net Income to Total Assets                          27.447    0.000
 ROA(A) before interest and % after tax              24.356    0.000
 ROA(B) before interest and depreciation after tax   23.435    0.000
 ROA(C) before interest and depreciation before...   22.305    0.000
 Net worth/Assets                                    21.333    0.000
...                                                     ...      ...
 Inventory/Current Liability                         -0.068    0.946
 Long-term Liability to Current Assets               -0.064    0.949
 Cash Flow to Sales                                  -0.040    0.968
 Realized Sales Gross Profit Growth Rate              0.038    0.970
 Operating Profit Rate                                0.019    0.985

[93 rows x 2 columns]

In [ ]:
#1類對多類的卡方檢定

qv3=[' Net Income Flag',' Liability-Assets Flag']
alist = []
pvlist = []
name = []
for i in qv3:
  cr=stats.chi2_contingency(pd.crosstab(dataMinMax['Bankrupt?'],dataMinMax[i]))
  pvlist.append(cr[1:2])
  alist.append(cr[0:1])
  name.append(i)
pd.set_option('display.float_format',lambda x:'%.3f'%x)
result=pd.DataFrame(alist,name,columns=['Chi-Square'])
pvlist2 = [item for t in pvlist for item in t] #Tuple to List
result.insert(1,'p_value',pvlist2)
result=result.sort_values(by=['p_value'])[::-1]
result

Chi-Square  p_value
 Net Income Flag             0.000    1.000
 Liability-Assets Flag     110.138    0.000

In [ ]:
dataP=dataMinMax[[' Liability-Assets Flag',' ROA(A) before interest and % after tax',' ROA(B) before interest and depreciation after tax',
       ' ROA(C) before interest and depreciation before interest',' Net worth/Assets', ' Debt ratio %',' Persistent EPS in the Last Four Seasons',
       ' Per Share Net profit before tax (Yuan 瞼)', ' Borrowing dependency',' Net Value Per Share (A)', ' Net Value Per Share (B)',
       ' Net Value Per Share (C)', ' Operating Profit Per Share (Yuan 瞼)',' Operating profit/Paid-in capital', ' Tax rate (A)',
       ' Operating Gross Margin', ' Realized Sales Gross Margin',' Cash Flow Per Share', ' Cash flow rate',' Contingent liabilities/Net worth',
       ' Net Value Growth Rate',' Cash Reinvestment %', ' Total Asset Growth Rate',' After-tax Net Profit Growth Rate',
       ' Regular Net Profit Growth Rate',' Quick Ratio', ' Research and development expense rate',' Net Income to Total Assets',
       ' Retained Earnings to Total Assets',' Net profit before tax/Paid-in capital',' Current Liability to Assets', ' Working Capital to Total Assets',
       " Net Income to Stockholder's Equity",' Current Liability to Current Assets', ' Liability to Equity',' Current Liability to Equity',
       ' Current Liabilities/Equity',' Working Capital/Equity', ' Total expense/Assets',' Equity to Long-term Liability', ' CFO to Assets',
       ' Cash/Total Assets',' Gross Profit to Sales',' Operating profit per person', ' Quick Assets/Total Assets',' Equity to Liability',
       ' Cash/Current Liability',' Operating Funds to Liability',' Inventory and accounts receivable/Net value',' Fixed Assets Turnover Frequency',
       ' Cash Flow to Total Assets',' Total Asset Turnover', ' Fixed Assets to Assets',' Cash Flow to Equity', ' Current Assets/Total Assets',
       ' Cash Flow to Liability', ' Revenue per person',' Total assets to GNP price', ' Quick Asset Turnover Rate']]

#標準化&降維後的P值小於0.05的欄位當自變數的混淆矩陣

In [ ]:
#降維
from sklearn.decomposition import PCA
pca = PCA(n_components="mle") #可以將引數設定為"mle",此時PCA類會用MLE演算法根據特徵的方差分佈情況自己去選擇一定數量的主成分特徵來降維(此範例會有56筆)
principalComponents = pca.fit_transform(dataP)
dataPPCA = pd.DataFrame(data=principalComponents)
dataPPCA.head()

0      1      2      3      4      5      6      7      8      9   ...  \
0  0.597 -0.005  0.164 -0.172 -0.251 -0.203 -0.088 -0.151  0.103  0.095  ...   
1  0.710 -0.002  0.057 -0.158 -0.158 -0.015 -0.142 -0.017  0.053  0.025  ...   
2 -0.068  0.258 -0.098 -0.244  0.073 -0.287  0.055  0.076 -0.081  0.022  ...   
3  0.688  0.471  0.313 -0.116  0.503 -0.148  0.010 -0.072  0.048 -0.001  ...   
4  0.365 -0.061  0.062 -0.176 -0.153 -0.066 -0.086  0.016  0.077 -0.024  ...   

      46     47     48     49     50     51     52     53     54     55  
0 -0.005  0.001 -0.000 -0.000  0.000 -0.000  0.000 -0.000 -0.000  0.000  
1  0.003 -0.000  0.000  0.000  0.000  0.000  0.002  0.000 -0.000 -0.000  
2  0.006 -0.001  0.007 -0.007  0.001  0.000  0.005  0.000  0.010 -0.000  
3 -0.002  0.001  0.000 -0.000 -0.000 -0.000 -0.000 -0.000  0.000  0.000  
4 -0.001  0.002 -0.000 -0.000  0.000 -0.000 -0.000 -0.000 -0.000  0.000  

[5 rows x 56 columns]

In [ ]:
X=dataPPCA[dataPPCA.columns] #降維後的欄位
y=dataMinMax['Bankrupt?'] #標準化後的Bankrupt?
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25 ,random_state=333)

決策樹

In [ ]:
from sklearn import tree
DT = tree.DecisionTreeClassifier(max_depth=10)
DT= DT.fit(X, y)

In [ ]:
#訓練
DT_pred= DT.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,DT_pred))
print("======================================================\n")
print(classification_report(y_train,DT_pred))

[[4934    3]
 [  39  138]]

              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00      4937
         1.0       0.98      0.78      0.87       177

    accuracy                           0.99      5114
   macro avg       0.99      0.89      0.93      5114
weighted avg       0.99      0.99      0.99      5114



In [ ]:
#測試
DT_pred= DT.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,DT_pred))
print("======================================================\n")
print(classification_report(y_test,DT_pred))

[[1661    1]
 [  13   30]]

              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00      1662
         1.0       0.97      0.70      0.81        43

    accuracy                           0.99      1705
   macro avg       0.98      0.85      0.90      1705
weighted avg       0.99      0.99      0.99      1705



隨機森林

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=15,max_features="sqrt",oob_score=True,random_state=3)
RF.fit(X_train.values,y_train.values)

/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:560: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(


RandomForestClassifier(max_features='sqrt', n_estimators=15, oob_score=True,
                       random_state=3)

In [ ]:
#訓練
RF_pred= RF.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,RF_pred))
print("======================================================\n")
print(classification_report(y_train,RF_pred))

[[4937    0]
 [  14  163]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      4937
         1.0       1.00      0.92      0.96       177

    accuracy                           1.00      5114
   macro avg       1.00      0.96      0.98      5114
weighted avg       1.00      1.00      1.00      5114



In [ ]:
#測試
RF_pred= RF.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,RF_pred))
print("======================================================\n")
print(classification_report(y_test,RF_pred))

[[1654    8]
 [  37    6]]

              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      1662
         1.0       0.43      0.14      0.21        43

    accuracy                           0.97      1705
   macro avg       0.70      0.57      0.60      1705
weighted avg       0.96      0.97      0.97      1705



羅吉斯回歸

In [ ]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(solver='liblinear')
LR.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [ ]:
#訓練
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_train)
print(confusion_matrix(y_train,LR_pred))
print("======================================================\n")
print(classification_report(y_train,LR_pred))

[[4931    6]
 [ 158   19]]

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98      4937
         1.0       0.76      0.11      0.19       177

    accuracy                           0.97      5114
   macro avg       0.86      0.55      0.59      5114
weighted avg       0.96      0.97      0.96      5114



In [ ]:
#測試
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_test)
print(confusion_matrix(y_test,LR_pred))
print("======================================================\n")
print(classification_report(y_test,LR_pred))

[[1654    8]
 [  35    8]]

              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      1662
         1.0       0.50      0.19      0.27        43

    accuracy                           0.97      1705
   macro avg       0.74      0.59      0.63      1705
weighted avg       0.97      0.97      0.97      1705



KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3) #K值(n_neighbors)預設為5
knn.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
#訓練
knn_pred= knn.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,knn_pred))
print("======================================================\n")
print(classification_report(y_train,knn_pred))

[[4924   13]
 [ 104   73]]

              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      4937
         1.0       0.85      0.41      0.56       177

    accuracy                           0.98      5114
   macro avg       0.91      0.70      0.77      5114
weighted avg       0.97      0.98      0.97      5114



In [ ]:
#測試
knn_pred= knn.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,knn_pred))
print("======================================================\n")
print(classification_report(y_test,knn_pred))

[[1658    4]
 [  31   12]]

              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      1662
         1.0       0.75      0.28      0.41        43

    accuracy                           0.98      1705
   macro avg       0.87      0.64      0.70      1705
weighted avg       0.98      0.98      0.97      1705



SVM

In [ ]:
from sklearn import svm 
clf = svm.SVC(kernel = 'linear') 
clf.fit(X_train,y_train) 

SVC(kernel='linear')

In [ ]:
#訓練
from sklearn.metrics import classification_report,confusion_matrix
clf_tpred= clf.predict(X_train)
print(confusion_matrix(y_train,clf_tpred))
print("======================================================\n")
print(classification_report(y_train,clf_tpred))

[[4936    1]
 [ 170    7]]

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98      4937
         1.0       0.88      0.04      0.08       177

    accuracy                           0.97      5114
   macro avg       0.92      0.52      0.53      5114
weighted avg       0.96      0.97      0.95      5114



In [ ]:
#測試
clf_pred= clf.predict(X_test)
print(confusion_matrix(y_test,clf_pred))
print("======================================================\n")
print(classification_report(y_test,clf_pred))

[[1661    1]
 [  42    1]]

              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      1662
         1.0       0.50      0.02      0.04        43

    accuracy                           0.97      1705
   macro avg       0.74      0.51      0.52      1705
weighted avg       0.96      0.97      0.96      1705

