請就所提供的資料以財務特徵(X1-X95)預測公司是否破產(Y)，並新增衍生變數，比較不同的機器學習模型，並說明分析結果

(Precision, Recall, Accuracy若未達0.9，請說明如何發展衍生變數使模式具有良好的預測能力)。

類別:
Net Income Flag(94)、Liability-Assets Flag(85)、Bankrupt?

#載入檔案和套件

In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import statsmodels.api as sm
from scipy import stats
from sklearn import metrics
from imblearn.under_sampling import RandomUnderSampler

#原始資料75:25

In [21]:
df=pd.read_excel("/content/drive/MyDrive/機器學習/闖關/預測公司破產資料.xlsx")

In [ ]:
f=df.groupby('Bankrupt?')
frequence=f.size()
flist=pd.DataFrame(frequence,columns=['Frequence_是否破產'])
f=df.groupby('Bankrupt?')
percentage=f.size()/len(df)
plist=pd.DataFrame(percentage,columns=['Percentage_是否破產'])
a=flist.merge(plist,on = 'Bankrupt?')
a

Frequence_是否破產  Percentage_是否破產
Bankrupt?                                 
0.0                  6599         0.967737
1.0                   220         0.032263

In [22]:
data=df

In [ ]:
#給下面自變數X取除了Bankrupt?以外的欄位名稱，不然一個一個打會打到亂掉
a25=data.copy()
a25=a25.drop('Bankrupt?',axis=1)

In [ ]:
X=a25[a25.columns]
y=data['Bankrupt?']
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25 ,random_state=33)

決策樹

In [ ]:
from sklearn import tree
DT = tree.DecisionTreeClassifier(max_depth=2)
DT= DT.fit(X_train, y_train)

In [ ]:
#訓練
DT_pred= DT.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,DT_pred))
print("======================================================\n")
print(classification_report(y_train,DT_pred))

[[4941    0]
 [ 173    0]]

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98      4941
         1.0       0.00      0.00      0.00       173

    accuracy                           0.97      5114
   macro avg       0.48      0.50      0.49      5114
weighted avg       0.93      0.97      0.95      5114



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#測試
DT_pred= DT.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,DT_pred))
print("======================================================\n")
print(classification_report(y_test,DT_pred))

[[1658    0]
 [  47    0]]

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.99      1658
         1.0       0.00      0.00      0.00        47

    accuracy                           0.97      1705
   macro avg       0.49      0.50      0.49      1705
weighted avg       0.95      0.97      0.96      1705



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


隨機森林

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=25,max_features="sqrt",oob_score=True)
RF.fit(X_train.values,y_train.values)

RandomForestClassifier(max_features='sqrt', n_estimators=25, oob_score=True)

In [ ]:
#訓練
RF_pred= RF.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,RF_pred))
print("======================================================\n")
print(classification_report(y_train,RF_pred))

[[4941    0]
 [   5  168]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      4941
         1.0       1.00      0.97      0.99       173

    accuracy                           1.00      5114
   macro avg       1.00      0.99      0.99      5114
weighted avg       1.00      1.00      1.00      5114



/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


In [ ]:
#測試
RF_pred= RF.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,RF_pred))
print("======================================================\n")
print(classification_report(y_test,RF_pred))

[[1653    5]
 [  40    7]]

              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      1658
         1.0       0.58      0.15      0.24        47

    accuracy                           0.97      1705
   macro avg       0.78      0.57      0.61      1705
weighted avg       0.97      0.97      0.97      1705



/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


羅吉斯回歸

In [ ]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(solver='newton-cg')
LR.fit(X_train, y_train)

In [ ]:
#訓練
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_train)
print(confusion_matrix(y_train,LR_pred))
print("======================================================\n")
print(classification_report(y_train,LR_pred))

[[4926   15]
 [ 169    4]]

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98      4941
         1.0       0.21      0.02      0.04       173

    accuracy                           0.96      5114
   macro avg       0.59      0.51      0.51      5114
weighted avg       0.94      0.96      0.95      5114



In [ ]:
#測試
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_test)
print(confusion_matrix(y_test,LR_pred))
print("======================================================\n")
print(classification_report(y_test,LR_pred))

[[1647   11]
 [  47    0]]

              precision    recall  f1-score   support

         0.0       0.97      0.99      0.98      1658
         1.0       0.00      0.00      0.00        47

    accuracy                           0.97      1705
   macro avg       0.49      0.50      0.49      1705
weighted avg       0.95      0.97      0.96      1705



KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
#訓練
knn_pred= knn.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,knn_pred))
print("======================================================\n")
print(classification_report(y_train,knn_pred))

[[4935    6]
 [ 149   24]]

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98      4941
         1.0       0.80      0.14      0.24       173

    accuracy                           0.97      5114
   macro avg       0.89      0.57      0.61      5114
weighted avg       0.96      0.97      0.96      5114



In [ ]:
#測試
knn_pred= knn.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,knn_pred))
print("======================================================\n")
print(classification_report(y_test,knn_pred))

[[1648   10]
 [  46    1]]

              precision    recall  f1-score   support

         0.0       0.97      0.99      0.98      1658
         1.0       0.09      0.02      0.03        47

    accuracy                           0.97      1705
   macro avg       0.53      0.51      0.51      1705
weighted avg       0.95      0.97      0.96      1705



#向下取樣75:25

In [23]:
#給下面自變數X取除了Bankrupt?以外的欄位名稱，不然一個一個打會打到亂掉
a25=data.copy()

In [24]:
X=a25[a25.columns]
y=data['Bankrupt?']
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25 ,random_state=33)
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(sampling_strategy=0.3)
X_resampled, y_resampled = rus.fit_resample(X_train, y_train)

In [25]:
# X_resampled.to_excel("75比25向下取樣X_resampled.xlsx")

決策樹

In [ ]:
from sklearn import tree
DT = tree.DecisionTreeClassifier(max_depth=2)
DT= DT.fit(X_resampled, y_resampled)

In [ ]:
#訓練
DT_pred= DT.predict(X_resampled)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_resampled,DT_pred))
print("======================================================\n")
print(classification_report(y_resampled,DT_pred))

[[576   0]
 [  0 173]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       576
         1.0       1.00      1.00      1.00       173

    accuracy                           1.00       749
   macro avg       1.00      1.00      1.00       749
weighted avg       1.00      1.00      1.00       749



In [ ]:
#測試
DT_pred= DT.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,DT_pred))
print("======================================================\n")
print(classification_report(y_test,DT_pred))

[[1658    0]
 [   0   47]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1658
         1.0       1.00      1.00      1.00        47

    accuracy                           1.00      1705
   macro avg       1.00      1.00      1.00      1705
weighted avg       1.00      1.00      1.00      1705



隨機森林

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=25,max_features="sqrt",oob_score=True)
RF.fit(X_resampled.values,y_resampled.values)

RandomForestClassifier(max_features='sqrt', n_estimators=25, oob_score=True)

In [ ]:
#訓練
RF_pred= RF.predict(X_resampled)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_resampled,RF_pred))
print("======================================================\n")
print(classification_report(y_resampled,RF_pred))

[[576   0]
 [  0 173]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       576
         1.0       1.00      1.00      1.00       173

    accuracy                           1.00       749
   macro avg       1.00      1.00      1.00       749
weighted avg       1.00      1.00      1.00       749



/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


In [ ]:
#測試
RF_pred= RF.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,RF_pred))
print("======================================================\n")
print(classification_report(y_test,RF_pred))

[[1656    2]
 [   0   47]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1658
         1.0       0.96      1.00      0.98        47

    accuracy                           1.00      1705
   macro avg       0.98      1.00      0.99      1705
weighted avg       1.00      1.00      1.00      1705



/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


羅吉斯回歸

In [ ]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(solver='newton-cg')
LR.fit(X_resampled, y_resampled)

In [ ]:
#訓練
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_resampled)
print(confusion_matrix(y_resampled,LR_pred))
print("======================================================\n")
print(classification_report(y_resampled,LR_pred))

[[551  25]
 [145  28]]

              precision    recall  f1-score   support

         0.0       0.79      0.96      0.87       576
         1.0       0.53      0.16      0.25       173

    accuracy                           0.77       749
   macro avg       0.66      0.56      0.56       749
weighted avg       0.73      0.77      0.72       749



In [ ]:
#測試 
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_test)
print(confusion_matrix(y_test,LR_pred))
print("======================================================\n")
print(classification_report(y_test,LR_pred))

[[1591   67]
 [  42    5]]

              precision    recall  f1-score   support

         0.0       0.97      0.96      0.97      1658
         1.0       0.07      0.11      0.08        47

    accuracy                           0.94      1705
   macro avg       0.52      0.53      0.53      1705
weighted avg       0.95      0.94      0.94      1705



KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3) 
knn.fit(X_resampled, y_resampled)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
#訓練
knn_pred= knn.predict(X_resampled)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_resampled,knn_pred))
print("======================================================\n")
print(classification_report(y_resampled,knn_pred))

[[559  17]
 [ 77  96]]

              precision    recall  f1-score   support

         0.0       0.88      0.97      0.92       576
         1.0       0.85      0.55      0.67       173

    accuracy                           0.87       749
   macro avg       0.86      0.76      0.80       749
weighted avg       0.87      0.87      0.86       749



In [ ]:
#測試
knn_pred= knn.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,knn_pred))
print("======================================================\n")
print(classification_report(y_test,knn_pred))

[[1470  188]
 [  37   10]]

              precision    recall  f1-score   support

         0.0       0.98      0.89      0.93      1658
         1.0       0.05      0.21      0.08        47

    accuracy                           0.87      1705
   macro avg       0.51      0.55      0.51      1705
weighted avg       0.95      0.87      0.91      1705



#原始資料90:10

In [ ]:
#給下面自變數X取除了Bankrupt?以外的欄位名稱，不然一個一個打會打到亂掉
a10=data.copy()
a10=a10.drop('Bankrupt?',axis=1)

In [ ]:
X=a10[a10.columns]
y=data['Bankrupt?']
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size = 0.10 ,random_state=33)

決策樹

In [ ]:
from sklearn import tree
DT = tree.DecisionTreeClassifier(max_depth=2)
DT= DT.fit(X_train, y_train)

In [ ]:
#訓練
DT_pred= DT.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,DT_pred))
print("======================================================\n")
print(classification_report(y_train,DT_pred))

[[5923   14]
 [ 171   29]]

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98      5937
         1.0       0.67      0.14      0.24       200

    accuracy                           0.97      6137
   macro avg       0.82      0.57      0.61      6137
weighted avg       0.96      0.97      0.96      6137



In [ ]:
#測試
DT_pred= DT.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,DT_pred))
print("======================================================\n")
print(classification_report(y_test,DT_pred))

[[659   3]
 [ 17   3]]

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.99       662
         1.0       0.50      0.15      0.23        20

    accuracy                           0.97       682
   macro avg       0.74      0.57      0.61       682
weighted avg       0.96      0.97      0.96       682



隨機森林

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=25,max_features="sqrt",oob_score=True)
RF.fit(X_train.values,y_train.values)

RandomForestClassifier(max_features='sqrt', n_estimators=25, oob_score=True)

In [ ]:
#訓練
RF_pred= RF.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,RF_pred))
print("======================================================\n")
print(classification_report(y_train,RF_pred))

[[5937    0]
 [   5  195]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      5937
         1.0       1.00      0.97      0.99       200

    accuracy                           1.00      6137
   macro avg       1.00      0.99      0.99      6137
weighted avg       1.00      1.00      1.00      6137



/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


In [ ]:
#測試
RF_pred= RF.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,RF_pred))
print("======================================================\n")
print(classification_report(y_test,RF_pred))

[[661   1]
 [ 19   1]]

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.99       662
         1.0       0.50      0.05      0.09        20

    accuracy                           0.97       682
   macro avg       0.74      0.52      0.54       682
weighted avg       0.96      0.97      0.96       682



/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


羅吉斯回歸

In [ ]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(solver='newton-cg')
LR.fit(X_train, y_train)

In [ ]:
#訓練
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_train)
print(confusion_matrix(y_train,LR_pred))
print("======================================================\n")
print(classification_report(y_train,LR_pred))

[[5921   16]
 [ 195    5]]

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98      5937
         1.0       0.24      0.03      0.05       200

    accuracy                           0.97      6137
   macro avg       0.60      0.51      0.51      6137
weighted avg       0.94      0.97      0.95      6137



In [ ]:
#測試
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_test)
print(confusion_matrix(y_test,LR_pred))
print("======================================================\n")
print(classification_report(y_test,LR_pred))

[[658   4]
 [ 20   0]]

              precision    recall  f1-score   support

         0.0       0.97      0.99      0.98       662
         1.0       0.00      0.00      0.00        20

    accuracy                           0.96       682
   macro avg       0.49      0.50      0.49       682
weighted avg       0.94      0.96      0.95       682



KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3) 
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
#訓練
knn_pred= knn.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,knn_pred))
print("======================================================\n")
print(classification_report(y_train,knn_pred))

[[5932    5]
 [ 168   32]]

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.99      5937
         1.0       0.86      0.16      0.27       200

    accuracy                           0.97      6137
   macro avg       0.92      0.58      0.63      6137
weighted avg       0.97      0.97      0.96      6137



In [ ]:
#測試
knn_pred= knn.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,knn_pred))
print("======================================================\n")
print(classification_report(y_test,knn_pred))

[[659   3]
 [ 20   0]]

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98       662
         1.0       0.00      0.00      0.00        20

    accuracy                           0.97       682
   macro avg       0.49      0.50      0.49       682
weighted avg       0.94      0.97      0.95       682



#向下取樣90:10

In [26]:
#給下面自變數X取除了Bankrupt?以外的欄位名稱，不然一個一個打會打到亂掉
a10=data.copy()

In [27]:
X=a10[a10.columns]
y=data['Bankrupt?']
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size = 0.10 ,random_state=33)
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(sampling_strategy=0.3)
X_resampled, y_resampled = rus.fit_resample(X_train, y_train)

In [28]:
# X_resampled.to_excel("90比10向下取樣X_resampled.xlsx")

決策樹

In [ ]:
from sklearn import tree
DT = tree.DecisionTreeClassifier(max_depth=2)
DT= DT.fit(X_resampled, y_resampled)

In [ ]:
#訓練
DT_pred= DT.predict(X_resampled)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_resampled,DT_pred))
print("======================================================\n")
print(classification_report(y_resampled,DT_pred))

[[666   0]
 [  0 200]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       666
         1.0       1.00      1.00      1.00       200

    accuracy                           1.00       866
   macro avg       1.00      1.00      1.00       866
weighted avg       1.00      1.00      1.00       866



In [ ]:
#測試
DT_pred= DT.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,DT_pred))
print("======================================================\n")
print(classification_report(y_test,DT_pred))

[[662   0]
 [  0  20]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       662
         1.0       1.00      1.00      1.00        20

    accuracy                           1.00       682
   macro avg       1.00      1.00      1.00       682
weighted avg       1.00      1.00      1.00       682



隨機森林

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=25,max_features="sqrt",oob_score=True)
RF.fit(X_resampled.values,y_resampled.values)

RandomForestClassifier(max_features='sqrt', n_estimators=25, oob_score=True)

In [ ]:
#訓練
RF_pred= RF.predict(X_resampled)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_resampled,RF_pred))
print("======================================================\n")
print(classification_report(y_resampled,RF_pred))

[[666   0]
 [  0 200]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       666
         1.0       1.00      1.00      1.00       200

    accuracy                           1.00       866
   macro avg       1.00      1.00      1.00       866
weighted avg       1.00      1.00      1.00       866



/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


In [ ]:
#測試
RF_pred= RF.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,RF_pred))
print("======================================================\n")
print(classification_report(y_test,RF_pred))

[[661   1]
 [  2  18]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       662
         1.0       0.95      0.90      0.92        20

    accuracy                           1.00       682
   macro avg       0.97      0.95      0.96       682
weighted avg       1.00      1.00      1.00       682



/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


羅吉斯回歸

In [ ]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(solver='newton-cg')
LR.fit(X_resampled, y_resampled)

In [ ]:
#訓練
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_resampled)
print(confusion_matrix(y_resampled,LR_pred))
print("======================================================\n")
print(classification_report(y_resampled,LR_pred))

[[638  28]
 [175  25]]

              precision    recall  f1-score   support

         0.0       0.78      0.96      0.86       666
         1.0       0.47      0.12      0.20       200

    accuracy                           0.77       866
   macro avg       0.63      0.54      0.53       866
weighted avg       0.71      0.77      0.71       866



In [ ]:
#測試
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_test)
print(confusion_matrix(y_test,LR_pred))
print("======================================================\n")
print(classification_report(y_test,LR_pred))

[[642  20]
 [ 19   1]]

              precision    recall  f1-score   support

         0.0       0.97      0.97      0.97       662
         1.0       0.05      0.05      0.05        20

    accuracy                           0.94       682
   macro avg       0.51      0.51      0.51       682
weighted avg       0.94      0.94      0.94       682



KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3) 
knn.fit(X_resampled, y_resampled)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
#訓練
knn_pred= knn.predict(X_resampled)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_resampled,knn_pred))
print("======================================================\n")
print(classification_report(y_resampled,knn_pred))

[[634  32]
 [ 90 110]]

              precision    recall  f1-score   support

         0.0       0.88      0.95      0.91       666
         1.0       0.77      0.55      0.64       200

    accuracy                           0.86       866
   macro avg       0.83      0.75      0.78       866
weighted avg       0.85      0.86      0.85       866



In [ ]:
#測試
knn_pred= knn.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,knn_pred))
print("======================================================\n")
print(classification_report(y_test,knn_pred))

[[589  73]
 [ 15   5]]

              precision    recall  f1-score   support

         0.0       0.98      0.89      0.93       662
         1.0       0.06      0.25      0.10        20

    accuracy                           0.87       682
   macro avg       0.52      0.57      0.52       682
weighted avg       0.95      0.87      0.91       682

